development:
  sessions:
    default:
      database: sv-stats-development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: sv-stats-test
      hosts:
        - localhost:27017
      options:
        max_retries: 0
        retry_interval: 0
production:
  sessions:
    default:
      hosts:
        - candidate.5.mongolayer.com:10061
        - candidate.6.mongolayer.com:10061
      username: <%= URI(ENV['MONGOHQ_URL']).user %>
      password: <%= URI(ENV['MONGOHQ_URL']).password %>
      database: app13829477
      options:
        timeout: 30
        pool_size: <%= ENV['SIDEKIQ_CONCURRENCY'] || 10 %>
